CREATE TABLE cliente (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome         VARCHAR(255) NOT NULL,
    cpf          VARCHAR(11)  NOT NULL,
    data_criacao TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_cliente_cpf UNIQUE (cpf)
);

CREATE INDEX idx_cliente_nome ON cliente (nome);
CREATE INDEX idx_cliente_cpf  ON cliente (cpf);
