CREATE TABLE IF NOT EXISTS conta (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_conta  VARCHAR(255)   NOT NULL,
    saldo         NUMERIC(19, 2) NOT NULL,
    cliente_id    BIGINT         NOT NULL,
    data_criacao  TIMESTAMP WITH TIME ZONE NOT NULL,
    versao        BIGINT         NOT NULL,
    CONSTRAINT uk_conta_numero  UNIQUE (numero_conta),
    CONSTRAINT fk_conta_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (id)
);

CREATE INDEX IF NOT EXISTS idx_conta_cliente_id ON conta (cliente_id);
