CREATE TABLE IF NOT EXISTS conta (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_banco    VARCHAR(255)   NOT NULL,
    numero_conta    VARCHAR(255)   NOT NULL,
    digito_conta    VARCHAR(255)   NOT NULL,
    numero_agencia  VARCHAR(255)   NOT NULL,
    digito_agencia  VARCHAR(255),
    saldo           NUMERIC(19, 2) NOT NULL,
    cliente_id      BIGINT         NOT NULL,
    data_criacao    TIMESTAMP WITH TIME ZONE NOT NULL,
    versao          BIGINT         NOT NULL,
    CONSTRAINT uk_conta_banco_conta_agencia  UNIQUE (codigo_banco, numero_conta, digito_conta, numero_agencia, digito_agencia),
    CONSTRAINT fk_conta_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (id)
);

CREATE INDEX IF NOT EXISTS idx_conta_cliente_id ON conta (cliente_id);
