CREATE TABLE transacao (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_origem_id   BIGINT         NOT NULL,
    conta_destino_id  BIGINT         NOT NULL,
    valor             NUMERIC(19, 2) NOT NULL,
    status            VARCHAR(20)    NOT NULL,
    correlation_id    VARCHAR(255)   NOT NULL,
    data_criacao      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_transacao_origem  FOREIGN KEY (conta_origem_id)  REFERENCES conta (id),
    CONSTRAINT fk_transacao_destino FOREIGN KEY (conta_destino_id) REFERENCES conta (id)
);

CREATE INDEX idx_transacao_conta_origem  ON transacao (conta_origem_id);
CREATE INDEX idx_transacao_conta_destino ON transacao (conta_destino_id);
CREATE INDEX idx_transacao_correlation   ON transacao (correlation_id);
