CREATE TABLE historico (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id         BIGINT         NOT NULL,
    tipo_movimento   VARCHAR(10)    NOT NULL,
    valor            NUMERIC(19, 2) NOT NULL,
    saldo_anterior   NUMERIC(19, 2) NOT NULL,
    saldo_posterior  NUMERIC(19, 2) NOT NULL,
    data_criacao     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_historico_conta FOREIGN KEY (conta_id) REFERENCES conta (id)
);

CREATE INDEX idx_historico_data_criacao ON historico (data_criacao);
CREATE INDEX idx_historico_conta_id     ON historico (conta_id);
